package util.communicator;

public enum KeyboardMessage {
  KEYBOARD_KEY_LEFT,
  KEYBOARD_KEY_RIGHT,
  KEYBOARD_KEY_UP,
  KEYBOARD_KEY_DOWN,
  KEYBOARD_KEY_A,
  KEYBOARD_KEY_E,
  KEYBOARD_KEY_U,
  KEYBOARD_KEY_1,
  KEYBOARD_KEY_2,
  KEYBOARD_KEY_SPACE;
}